apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 namespace: dev
spec:
 replicas: 1
 selector:
  matchLabels:
   app: backend
 template:
  metadata:
   labels:
    app: backend
  spec:
   containers:
   - name: backend
     image: retailfactory/backend-r7:latest
     ports:
     - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
 name: backend
 namespace: dev
spec:
 type: NodePort
 selector:
  app: backend
 ports:
 - port: 3001
   targetPort: 3001
   nodePort: 30081
