apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        image: retailfactory/backend-r7:latest
