apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        image: retailfactory/frontend-r7:latest
